### ISSUE TITLE
Unable to use the custom connector.

### ISSUE THREAD

**Issue by BPurcell02** [tylerchessman/PBI_FRED_EIA#1]
Unable to view the Enpublica custom connector in the get data list.  The same issue has been mentioned in the YouTube tutorial comments.

**Comment by tylerchessman** [comment]
Hello, thanks for reaching out.  Can you provide a bit more detail?  For example, the connector won't likely appear in the initial list of "Common data sources".  You need to click **More** (to bring up the Get Data dialog box) to search for and select the connector.  Did you do this?  And (if the Desktop was open during install) did you first restart the PBI Desktop?

If necessary, please try to manually inspect/check the install.  The repo's Readme (https://github.com/tylerchessman/PBI_FRED_EIA/blob/main/README.md) shows the "manual" install steps:

- First, confirm the connector file ( Enpublica.pqx) was installed to the Custom Connectors folder.  If not, copy the connector file to the local [Documents]\Power BI Desktop\Custom Connectors folder. If the folder doesn't exist, create it.
- Secondly, check the permissions for the connector (Adjust the data extension security settings as needed; refer to https://learn.microsoft.com/en-us/power-bi/connect-data/desktop-connector-extensibility for instructions.)

![image](https://github.com/tylerchessman/PBI_FRED_EIA/assets/7661016/a5152131-b8a7-4ac8-b8bc-982b63d58424)

**Comment by BPurcell02** [comment]
Thanks for the response Tyler. 

I tried installing the exe file using Admin privledges.  I then created a folder in my documents and saved the PQX file there.  I changed the security settings as well.  No luck.

![image](https://github.com/tylerchessman/PBI_FRED_EIA/assets/76656626/b4faf1da-3763-4e6c-b86a-2e7035ef2025)
![image](https://github.com/tylerchessman/PBI_FRED_EIA/assets/76656626/53e85aa5-f6dd-48be-a48d-4bd1a14ae5fe)
![image](https://github.com/tylerchessman/PBI_FRED_EIA/assets/76656626/9150bac2-b9e9-47a5-a1f4-dc0a6a0917bf)

Not sure if this matters, but here's my version 
Version: 2.126.1261.0 64-bit (February 2024)

**Comment by tylerchessman** [comment]
Thanks for the follow up.  That is the version of the desktop I have as well.  Perhaps there is an Operating System or other security issue:
- What happens if you start/run Power BI Desktop as an administrator?
- You may try right clicking on the Enpublica.pqx file to "unblock" it (i.e. Right-click the file in Explorer, choose Properties, and choose Unblock).  This didn't seem to affect any of my laptops, but worth a try.
- Lastly, can you tell me what Operating System you are running? I have Windows 11, but if necessary, I could fire up a VM with another OS.

![image](https://github.com/tylerchessman/PBI_FRED_EIA/assets/7661016/bf132001-519c-4216-9ded-f514beecd079)

**Comment by BPurcell02** [comment]
I appreciate the help, but I'm not able to make it work.  I tried running powerbi as admin, I checked unblock, and it still didn't show.   I'm still on Windows 10

**Comment by tylerchessman** [comment]
Ok, thanks for trying!  I am going to setup a machine with Windows 10, and see if I can recreate the issue.  I will also reach out to some others for help, and will follow back up with any feedback/insights as soon as possible.

**Comment by tylerchessman** [comment]
Hello, I installed Windows 10 on a VM - but wasn't able to recreate the problem.
I did try working as a non-admin user; that didn't work unless I first manually created/copied the necessary folders/file underneath my own Documents folder (i.e. Documents\Power BI Desktop\Custom Connectors).  If you are not an admin on the machine, that could we worth a try.

Still waiting to get some additional feedback.  Just for grins, you may also want to try seeing if the connector shows up underneath the Online Services (who knows, maybe the search is wonky, or case sensitive).   Alternatively, you could try downloading one of the finished sample tutorials and try to refresh (confirm the connector is actually broken).

**Lastly,** I have temporarily uploaded the non-signed version of the connector (https://github.com/tylerchessman/PBI_FRED_EIA/blob/main/Tutorials/Utils/Enpublica.mez) to test.  I would remove Enpublica.pqx from the Custom Connectors file - put this mez file there instead - and go with the Options-Global-Security-Data Extensions option _(Not Recommended) Allow any extension to load without validation or warning_.

![image](https://github.com/tylerchessman/PBI_FRED_EIA/assets/7661016/6ae4c225-639c-4320-b882-fbb4eff97683)

**Comment by BPurcell02** [comment]
Thanks Tyler -- It worked.  I think the .mez file resolved my issues.  I appreciate you hunting this down.
